#!/bin/bash -evx


THIS="${0##*/}"

WORK="./lwrtmp-env"
CHROOT="$WORK/iso/chroot"
DISK="$1"
SQUASHFSSRC="$1/casper/filesystem.squashfs"

unsquashfs -d "$WORK" "$SQUASHFSSRC" > /dev/null
mkdir -p "$WORK/iso/disk"
cp -r "$DISK/." "$WORK/iso/disk"
unsquashfs -d "$CHROOT" "$SQUASHFSSRC" > /dev/null
cp -r dist "$WORK/iso"
cp -r scripts/. "$WORK/iso"

mount --bind /proc "$CHROOT/proc"
chroot "$WORK" /iso/lwr-prepare-chroot
umount "$CHROOT/proc"

rm -f "$WORK/iso/disk/casper/filesystem.squashfs"
chroot "$WORK" /iso/lwr-build-iso
cp "$WORK/iso/luwrain.iso" luwrain.iso

# OK!
