#!/bin/bash -evx
# Copyright 2020 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN project, licensed under the terms of GPL v.3

THIS="${0##*/}"

LWRISO_VERSION="$1"
LWRISO_LANG="$2"
[ -z "$LWRISO_VERSION" ] && echo "$THIS:no version given" >&2 && exit 1
[ -z "$LWRISO_LANG" ] && echo "$THIS:no lang given" >&2 && exit 1

cd /iso
. config.sh
. base.sh

echo "nameserver $LWRISO_NAMESERVER" > /etc/resolv.conf

find scripts.d -type f -executable | sort | while read l ; do
    echo Launching $l
    source "$l"
done

# Locale
#echo 'LANG="ru_RU.UTF-8"' > ./chroot/etc/default/locale
# For proper Russian characters in console
#sed -i -e s:'^ExecStart=.*$':'ExecStart=/bin/setupcon': ./chroot/lib/systemd/system/systemd-vconsole-setup.service

