#!/bin/bash -evx

cd /iso
. config.sh
. base.sh 

# Locale
#echo 'LANG="ru_RU.UTF-8"' > ./chroot/etc/default/locale
# For proper Russian characters in console
#sed -i -e s:'^ExecStart=.*$':'ExecStart=/bin/setupcon': ./chroot/lib/systemd/system/systemd-vconsole-setup.service

find scripts.d -type f -executable | sort | while read l ; do
    source "$l"
done &> /iso/log-scripts.txt

# ISO chroot prepared!
