#!/bin/bash -e

THIS="${0##*/}"

LWRISO_VERSION="$1"
LWRISO_LANG="$2"
[ -z "$LWRISO_VERSION" ] && echo "$THIS:no version given" >&2 && exit 1
[ -z "$LWRISO_LANG" ] && echo "$THIS:no lang given" >&2 && exit 1

cd /iso
. config.sh
. base.sh 

# Locale
#echo 'LANG="ru_RU.UTF-8"' > ./chroot/etc/default/locale
# For proper Russian characters in console
#sed -i -e s:'^ExecStart=.*$':'ExecStart=/bin/setupcon': ./chroot/lib/systemd/system/systemd-vconsole-setup.service

find scripts.d -type f -executable | sort | while read l ; do
    echo Launching $l
    source "$l"
done

echo ISO chroot prepared!
