#!/bin/sh -e

chroot ./chroot apt-get -y remove pulseaudio
#mkdir -p ./chroot/opt/luwrain-live/
#cp proba.wav ./chroot/opt/luwrain-live/greeting.wav

echo 'nameserver 192.168.1.1' > ./chroot/run/resolvconf/resolv.conf

cat <<EOF > ./chroot/etc/apt/sources.list
deb http://download.luwrain.org/ubuntu/ trusty main
deb http://ru.archive.ubuntu.com/ubuntu/ trusty main restricted
deb http://ru.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
deb http://ru.archive.ubuntu.com/ubuntu/ trusty universe
deb http://ru.archive.ubuntu.com/ubuntu/ trusty-updates universe
deb http://ru.archive.ubuntu.com/ubuntu/ trusty multiverse
deb http://ru.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
deb http://ru.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu trusty-security main restricted
deb http://security.ubuntu.com/ubuntu trusty-security universe
deb http://security.ubuntu.com/ubuntu trusty-security multiverse

EOF

chroot ./chroot apt-get update
chroot ./chroot apt-get -y --force-yes install libncursesw5 vorbis-tools
chroot ./chroot apt-get -y --force-yes install voiceman rhvoice espeak mbrola mbrola-en1 yasr eflite freespeech
chroot ./chroot apt-get -y --force-yes install luwrain-live

chroot ./chroot systemctl set-default multi-user.target

mkdir -p './chroot/etc/systemd/system/getty@tty1.service.d'

cat <<EOF > './chroot/etc/systemd/system/getty@tty1.service.d/override.conf'
[Service]
ExecStart=
ExecStart=-/bin/openvt -c 1 -w -s -f /etc/rc.livecd
Type=idle
EOF

cd ./chroot/etc/systemd
sed -i -e s/'^.*NAutoVTs.*$'/'NAutoVTs=0'/  logind.conf
cd ../../..

chroot ./chroot systemctl enable getty@tty1

cd ./chroot/etc/yasr
sed -i -e s/'^\(synthesizer=.*\)$'/'#\1'/ yasr.conf
sed -i -e s/'^.*synthesizer.*emacspeak.*$'/'synthesizer=emacspeak server'/ yasr.conf
sed -i -e s/'^\(synthesizer port=.*\)$'/'#\1'/ yasr.conf
sed -i -e s:'^.*synthesizer port.*eflite.*$':'synthesizer port=|/usr/bin/voiceman-emacspeak': yasr.conf
cd ../../..

cat <<EOF > ./chroot/etc/rc.livecd
#!/bin/bash

for i in PCM Speaker; do
    /usr/bin/amixer set $i 100% &> /dev/null
    /usr/bin/amixer set $i unmute &> /dev/null
done
/usr/bin/amixer set Master 80% &> /dev/null
/usr/bin/amixer set Master unmute &> /dev/null

/usr/bin/voicemand -d
/usr/bin/greeter-ru
EOF

chmod 755 ./chroot/etc/rc.livecd

cat <<EOF > ./chroot/etc/voiceman.conf
# VoiceMan configuration for LUWRAIN distribution
# Michael Pozhidaev <michael.pozhidaev@gmail.com>

[Global]
inet socket port = 5511
socket = "/tmp/voiceman.socket"
log level = info
default language = rus

[characters]
default = "0123456789.,;:_-+=[]&<>""'/\\|?~\`!@#\$%^*(){}"
EOF

cat <<EOF > ./chroot/etc/voiceman.d/rhvoice-rus.output
[output]
name = RHVoice
type = command
lang = rus
synth command = "RHVoice -r %r -p %p | voiceman-trim --words"
alsa player command = "exec aplay -"
pitch num digits after dot = 2
pitch min = "0.1"
pitch aver = 1
pitch max = "1.9"
rate num digits after dot = 2
rate max = "0.5"
rate aver = 1.6
rate min = 2
EOF

cat <<EOF > ./chroot/etc/voiceman.d/mbrola-eng.output
[output]
name = mbrola
type = command
lang = eng
synth command = "freephone -h /usr/share/freespeech/lexicon -m | mbrola -f %p -v %v -t %r /usr/share/mbrola/en1/en1 - - | /usr/bin/voiceman-trim --words "
alsa player command = "exec aplay -t raw -f s16 -c 1 -r 16000"
replacements = "/usr/share/voiceman/replacements.mbrola"
pitch num digits after dot = 2
pitch min = 0.3
pitch aver = 1
pitch max = 2.5
rate num digits after dot = 2
rate min = 0.5
rate aver = 1
rate max = 3
volume num digits after dot = 2
volume min = 0
volume aver = 2.5
volume max = 10
EOF
