#!/bin/bash
set -e

# now we will try to grep the latest luwrain nightly and install it to the system

wget -O luwrain.tar.xz "https://download.luwrain.org/nightly/latest/luwrain-linux-x64-nightly-2022-07-05.tar.xz"
tar -xf luwrain.tar.xz
rm luwrain.tar.xz
mv ./luwrain-* luwrain

mv ./luwrain/lib/app/luwrain-base.jar ./luwrain/jar/
rm -R luwrain/lib
mkdir -p ./config/includes.chroot/opt/
mv ./luwrain ./config/includes.chroot/opt/luwrain

