#!/bin/bash -evx

cd /iso
. base.sh
echo "nameserver $LWRISO_NAMESERVER" > "/etc/resolv.conf"
export DEBIAN_FRONTEND=noninteractive
export HOME=/home/$LWRISO_USER

find scripts.d -type f -executable | sort | while read l ; do
    echo Running "$l"
    source "$l"
done

# ISO chroot prepared!
