#!/bin/bash -e
# Copyright 2012-2016 Michael Pozhidaev <michael.pozhidaev@gmail.com>
# This file is part of LUWRAIN

rm -rf ./out ./luwrain
ant
cp -r out/bundles/luwrain ./luwrain
sed -i -e s'|^app.classpath=$|app.classpath=jar/luwrain.jar:jar/luwrain-base.jar|' luwrain/app/package.cfg
rm -rf out
