#!/bin/bash -e
# Copyright 2012-2018 Michael Pozhidaev <michael.pozhidaev@gmail.com>

apt-get update
apt-get -y --force-yes  install openjdk-8-jdk openjfx ant
cd /pkg
rm -rf out luwrain
ant -lib /usr/share/java/openjfx/lib
cp -r out/bundles/luwrain ./luwrain
rm -rf out
mv luwrain/app/*.txt luwrain
sed -i -e s'|^app.classpath=$|app.classpath=jar/luwrain.jar:jar/luwrain-base.jar|' luwrain/app/luwrain.cfg
