#!/bin/sh

set -e



lb config noauto \
	--clean \
	--debian-installer live \
	--archive-areas "main contrib non-free" \
	--linux-packages "linux-image linux-headers" \
	--bootappend-live="boot=live components locales=ru_RU.UTF-8 noautologin keyboard-layouts=us,ru keyboard-options=grp:lalt_lshift_toggle" \
	--source "false" \
"${@}"
