#!/bin/bash -e
# Copyright 2012-2018 Michael Pozhidaev <michael.pozhidaev@gmail.com>

THIS="${0##*/}"

IFACE="$1"
ESSID="$2"
PASSWD="$3"

[ -z "$IFACE" ] && echo "$THIS:interface not given" >&2 && exit 1
[ -z "$ESSID" ] && echo "$THIS:essid not given" >&2 && exit 1

killall wpa_supplicant &> /dev/null ||:
rfkill unblock all
ifconfig "$IFACE" up
iwconfig "$IFACE" mode managed
iwconfig "$IFACE" essid "$ESSID"

if [ -n "$PASSWD" ]; then
    echo "$PASSWD" | wpa_passphrase "$ESSID" > /tmp/.wpa.conf
    wpa_supplicant -B -Dwext -i "$IFACE" -c /tmp/.wpa.conf
fi

exec 2>&1
dhclient -v "$IFACE"
