#!/bin/bash -e
# Prints the level of the default battery on 'acpi' command output; returns 1, if there is no battery info 
# Copyright 2012-2018 Michael Pozhidaev <michael.pozhidaev@gmail.com>

VALUE="$(acpi 2> /dev/null)"

if ! echo "$VALUE" | egrep -qi '^battery [0-9]+: [a-z]+, [0-9]+%.*$'; then
exit 1
fi

echo "$VALUE" | sed s/'^battery [0-9]\+: [a-z]\+, \([0-9]\+\)%.*$'/'\1'/i
