#!/bin/bash -e
# Copyright 2012-2018 Michael Pozhidaev <michael.pozhidaev@gmail.com>

THIS="${0##*/}"

IFACE="$1"
[ -z "$IFACE" ] && echo "$THIS:interface not given" >&2 && exit 1

killall wpa_supplicant &> /dev/null ||:
killall dhclient &> /dev/null ||:
ifconfig "$IFACE" down
