#!/bin/bash
# Copyright 2012-2018 Michael Pozhidaev <michael.pozhidaev@gmail.com>

THIS="${0##*/}"

DEV_NAME="$1"
MOUNT_POINT="$2"

[ -z "$DEV_NAME" ] && echo "$THIS:no device path given" >&2 && exit 1
[ -z "$MOUNT_POINT" ] && echo "$THIS:no mount point given" >&2 && exit 1

VFAT_OPT='rw,nosuid,nodev,noexec,relatime,fmask=0111,dmask=0000,codepage=437,iocharset=iso8859-1,shortname=mixed,quiet,utf8,errors=remount-ro'

FS_TYPE="$(lsblk -o fstype  -d -n "$DEV_NAME")"

mkdir -p "$MOUNT_POINT"

if [ "$FS_TYPE" == vfat ]; then
    if     mount -o "$VFAT_OPT" "$DEV_NAME" "$MOUNT_POINT"; then
	exit 0 
    fi
fi

if mount "/$DEV_NAME" "$MOUNT_POINT"; then
    exit 0	
fi   

rmdir  "$MOUNT_POINT"
exit 1
