#!/bin/bash -e
# Copyright 2012-2018 Michael Pozhidaev <michael.pozhidaev@gmail.com>

THIS="${0##*/}"

VALUE="$1"

[ -z "$VALUE" ] && echo "$THIS:value to set not given" >&2 && exit 1

amixer set Master "$VALUE"%
