#!/bin/bash -e

THIS="${0##*/}"

[ -z "$1" ] && echo "ERROR: THIS: No destination distro" >&2 && exit 1
DISTRO="$1"

mkdir -p out
docker run --rm -i -v "$(pwd)/out:/out" "$DISTRO" bash -c 'apt-get update && \
apt-get install -y --no-install-recommends git g++ build-essential debhelper ca-certificates libgdbm-dev libgdbm-compat-dev && \
git clone https://github.com/marigostra/mbrola-suite && \
cd mbrola-suite && \
dpkg-buildpackage --build=binary -us -uc && \
mv /*.deb /out/'
