#!/bin/bash -e
# Copyright 2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

THIS="${0##*/}"
[ -z "$GPG_KEYS" ] && echo "ERROR: $THIS: No the GPG_KEYS variable" >&2 && exit 1

for i in debian:11 debian:12 ubuntu:jammy ubuntu:noble; do
    ./build-mbrola "$i" &
    ./build-rhvoice "$i" &
    ./build-voiceman "$i" &
    ./build-dwm "$i" &
    wait
    ./build-luwrain "$i"
    rm -f out/*dbgsym*
    ./repo-data $i
    rm -f out/*.deb
done
